drivers:
  size: 5

nodes:
  episodes: 200 #Can vary, but should be around 500 for convergence
  open_position_row: 1
  open_position_column: 1

critic:
  type: nn #table or nn
  dimensions: [15, 20, 30, 1]
  eligibility_decay: 0.99
  discount_factor: 0.99
  learning_rate: 0.001

actor:
  eligibility_decay: 0.9
  learning_rate: 0.1
  init_epsilon: 1
  epsilon_decay: 0.95
  discount_factor: 0.9